os:
  - linux

dist: focal

language: python
python:
  - "3.9"

services:
  - docker 

script:
  - python -m pytest -v
  - cp .env.example .env
  - docker-compose up -d
  - docker-compose ps

deploy:
  provider: heroku
  api_key:
    secure: mjONk/DWtF9rcCRN7yAvzEsGurWc4OdhXnN0dyHBy0CpfBYrgyGdraM+T/h80X7chl2V+zTivwjX4ddHWguhVDo+v0Ljxi/C5BGVXOhFg6WjXgzVkINinmUat9mpulIHwzQuv2YRuY4euzxrX+ZqnvA5ldhjBIoP6VekKemlOH8x5t5qpussy637M8J4KWS8++TymvixhG4JOAn0z0ElOele4kRI5owNiYBr9mv4jbvOjaSHTHm9S6jQd8VW7qh7hzslCAC+RUU05HsP7/OZ03In3uKgAM6I+GYovSQnu2nJ6qQqhBMrsvT6b1RvNFbm7UCD9v74JSDdVUE9Oh/Z/KxpI3Olp/RqNcsM/ZE7fvNO9C3bEpMNFKtW0iu4aMc3D5a8KADrKAS0nVq2NklUQps5JW8WBBw5E+CPH7RssHOvG9xH5zv4hvrpLpYubX1o2kgC4C2psPK6z0UgTkHNOKcKZdAHhEvmMHoisvWfh3/s74mbSUethedsKjBjm4AHrltPcBVx7LZk5mVH1mmd4sXXFUNyCeZpvWWdg2a01dRmaGqv6UcpehHPHLx4ekUIe+jxaiJaOwd+7oBuTXk4iDExmYbU0zm8e7K31Xc7q7DPQIxX8KyF3UZJq+DyGwccEZF49b3zA6GDOkvwiHSrf8LmRHm/E5Gdc48HVVTIrPo=
